# Generated by Django 5.0.1 on 2024-01-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_discription_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
